#!/bin/bash
[[ -a "$HOME/.vimrc" ]] && mv -f $HOME/.vimrc{,.pre}
[[ -a "$HOME/.ackrc" ]] && mv -f $HOME/.ackrc{,.pre}
[[ -a "$HOME/.zshrc" ]] && mv -f $HOME/.zshrc{,.pre}
ln -s $HOME/Documents/dotfiles/.vimrc $HOME/.vimrc
ln -s $HOME/Documents/dotfiles/.ackrc $HOME/.ackrc
ln -s $HOME/Documents/dotfiles/.zshrc $HOME/.zshrc
